changelog:
  exclude:
    labels:
      - skip-changelog
      - duplicate
      - invalid
      - wontfix
  categories:
    - title: 🚀 Features
      labels:
        - feature
        - enhancement
    - title: 🐛 Fixes
      labels:
        - fix
        - bug
        - bugfix
    - title: ⚡ Performance
      labels:
        - performance
        - perf
    - title: 🧰 CI / Release
      labels:
        - ci
        - release
        - build
    - title: 📝 Docs
      labels:
        - docs
        - documentation
    - title: 🔧 Maintenance
      labels:
        - chore
        - refactor
        - dependencies
